<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TRUFLAEGY29" name="tests.OrderCheckout" tests="2" failures="0" timestamp="19 Jan 2022 21:12:29 GMT" time="6.056" errors="1">
  <testcase name="Check_URL_Redirection" time="6.013" classname="tests.OrderCheckout"/>
  <testcase name="registerWith" time="0.043" classname="tests.OrderCheckout">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: registerWith([])
Arguments: [(java.lang.String)My Store,(java.lang.String)http://automationpractice.com/index.php,(java.lang.String)ubmntjgc@sharklasers.com,(java.lang.String)Password,(java.lang.String)Your order on My Store is complete.]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: registerWith([])
Arguments: [(java.lang.String)My Store,(java.lang.String)http://automationpractice.com/index.php,(java.lang.String)ubmntjgc@sharklasers.com,(java.lang.String)Password,(java.lang.String)Your order on My Store is complete.]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1225)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1123)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- registerWith -->
</testsuite> <!-- tests.OrderCheckout -->
